version: 2
updates:
    -   package-ecosystem: npm
        directory: '/'
        schedule:
            interval: weekly
        groups:
            storybook:
                patterns:
                    - "@storybook/*"
    -   package-ecosystem: github-actions
        directory: '/'
        schedule:
            interval: weekly
