name: Publish Package
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: read # Set top-level permissions to read only
jobs:
  publish:
    permissions:
      id-token: write # Required for OIDC
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.13.0

      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm ci

      - name: Audit dependencies
        run: npm audit --audit-level=high

      - name: Build & test the package
        run: |
          npm run test-storybook
          npm run test-unit
          npm run build --if-present

      - name: Publish package
        run: npm publish
