name: Storybook, Accessibility & Chromatic
on: pull_request

env:
  NODE_VERSION: 22.13.0

permissions:
  contents: read

jobs:
  storybook-accessibility:
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.57.0-noble
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run tests
        run: npm run test-storybook

  jsunit-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run tests
        run: npm run test-unit-coverage
        env:
          SB_URL: '${{ github.event.deployment_status.environment_url }}'

  chromatic:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
          CHROMATIC_SLUG: ${{ github.repository }}
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          skip: 'dependabot/**'
          externals: |
            fonts/**
            tokens/**
