name: Run Storybook, Accessibility & JSUnit tests.
on: pull_request
jobs:
  storybook-accessibility:
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.57.0-noble
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.13.0

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run tests
        run: npm run test-storybook

  jsunit-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.13.0

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run tests
        run: npm run test-unit-coverage
        env:
          SB_URL: '${{ github.event.deployment_status.environment_url }}'
